const data = {
  products: [
    {
      _id:'1',
      name:'Chanel Green Bag',
      category:'Bag',
      image: '../images/img_1.jpg',
      price: 1200,
      countInStock: 10,
      brand: 'Chanel',
      rating: 1.5,
      numReviews: 5,
      description: 'high quality product',
    },
    {
      _id:'2',
      name:'Chanel Blue Wallet',
      category:'Bag',
      image: '../images/img_2.jpg',
      price: 2400,
      countInStock: 20,
      brand: 'Chanel',
      rating: 2.5,
      numReviews: 4,
      description: 'high quality product',
    },
    {
      _id:'3',
      name:'Chanel Black Wallet',
      category:'Bag',
      image: '../images/img_3.jpg',
      price: 3200,
      countInStock: 0,
      brand: 'Chanel',
      rating: 3.0,
      numReviews: 3,
      description: 'high quality product',
    },
    {
      _id:'4',
      name:'Chanel Red Wallet',
      category:'Bag',
      image: '../images/img_4.jpg',
      price: 4800,
      countInStock: 13,
      brand: 'Chanel',
      rating: 4.5,
      numReviews: 2,
      description: 'high quality product',
    },
    {
      _id:'5',
      name:'Chanel Pink Bag',
      category:'Bag',
      image: '../images/img_5.jpg',
      price: 5000,
      countInStock: 50,
      brand: 'Chanel',
      rating: 5.0,
      numReviews: 1,
      description: 'high quality product',
    },
  ],
};

export default data;